# Generated by Django 5.0.7 on 2024-08-05 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='location_history',
            field=models.ManyToManyField(through='devices.LocationHistory', to='devices.location'),
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='locationhistory',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.RemoveField(
            model_name='schedulemaintenance',
            name='device',
        ),
        migrations.CreateModel(
            name='Device_Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('schedule_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.schedulemaintenance')),
            ],
        ),
        migrations.AddField(
            model_name='schedulemaintenance',
            name='device',
            field=models.ManyToManyField(through='devices.Device_Maintenance', to='devices.device'),
        ),
    ]
