# Generated by Django 5.0.7 on 2024-08-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_location_history_locationhistory_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemaintenance',
            name='date',
            field=models.DateField(),
        ),
    ]
