# Generated by Django 5.0.7 on 2024-08-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_post'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportrepairhistory',
            table='ReportRepairHistory',
        ),
    ]
