# Generated by Django 5.0.7 on 2024-08-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_job_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='locationhistory',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
