# Generated by Django 5.0.7 on 2024-08-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_job_end_date_alter_locationhistory_end_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='device_maintenance',
            table='Device_Maintenance',
        ),
    ]
